name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      timeout-minutes: 1
      with:
        node-version: 13.x
    - name: Build
      run: |
        yarn install
        yarn build
